services:

    # PgAdmin : https://www.pgadmin.org/
    # Used to manage the postgres database
    pgadmin:
        container_name: ${PROJECT_NAME}-pgadmin
        hostname: ${PROJECT_NAME}-database
        image: dpage/pgadmin4
        restart: always
        environment:
            PGADMIN_DEFAULT_EMAIL: ${PGADMIN_DEFAULT_EMAIL}
            PGADMIN_DEFAULT_PASSWORD: ${PGADMIN_DEFAULT_PASSWORD}
            PGADMIN_LISTEN_PORT: 80
            TZ: ${APP_TIMEZONE}
        ports:
            - "${PGADMIN_HTTP_PORT}:80"
        volumes:
            - pgadmin_data:/var/lib/pgadmin
        networks:
            - default
            - database_network

    # Redis cache database
    redis:
        image: redis/redis-stack
        ports:
            - "${REDIS_HTTP_PORT}:8001"

    # Mailhog : https://github.com/mailhog/MailHog
    # Used to catch emails sent by the application
    mailhog:
        container_name: ${PROJECT_NAME}-mailhog
        hostname: ${PROJECT_NAME}-mailhog
        image: mailhog/mailhog
        restart: always
        ports:
            - "${MAILHOG_SMTP_PORT}:1025"
            - "${MAILHOG_HTTP_PORT}:8025"
        networks:
            - default

# Declare volumes to mount
volumes:
    pgadmin_data: { }
